# Generated by Django 3.0.5 on 2022-02-25 14:25

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200, unique=True, verbose_name='Item city name')),
                ('start_date', models.DateField(db_index=True, verbose_name='Item start date')),
                ('end_date', models.DateField(db_index=True, verbose_name='Item end date')),
                ('price', models.FloatField(verbose_name='Item price')),
                ('status', models.CharField(choices=[('Never', 'Never'), ('Once', 'Once'), ('Seldom', 'Seldom'), ('Often', 'Often'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='Never', max_length=50, verbose_name='Item status')),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None, verbose_name='Item color')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
    ]
