# Generated by Django 2.2.6 on 2022-02-26 21:51

import colorfield.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='city',
            field=models.CharField(max_length=200, verbose_name='Item city name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None, verbose_name='Item color'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Item price'),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('Never', 'Never'), ('Once', 'Once'), ('Seldom', 'Seldom'), ('Often', 'Often'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=50, verbose_name='Item status'),
        ),
    ]
