# Generated by Django 2.2.6 on 2022-02-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20220225_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='end_date',
            field=models.DateField(db_index=True, verbose_name='Item end date'),
        ),
        migrations.AlterField(
            model_name='item',
            name='start_date',
            field=models.DateField(db_index=True, verbose_name='Item start date'),
        ),
    ]
