# Generated by Django 2.2.6 on 2022-02-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20220225_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='city',
            field=models.CharField(max_length=200, verbose_name='Item city name'),
        ),
    ]
