# Generated by Django 2.2.6 on 2022-02-25 20:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20220225_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1, message='Price can not be negative.')], verbose_name='Item price'),
        ),
    ]
