# Generated by Django 2.2.6 on 2022-02-25 20:55

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20220225_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None, verbose_name='Item color'),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('Never', 'Never'), ('Once', 'Once'), ('Seldom', 'Seldom'), ('Often', 'Often'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=50, verbose_name='Item status'),
        ),
    ]
